os:
  - windows
  - linux
  - osx
language: java
jdk:
  - oraclejdk11
env:
  - WORKDIR=singletonpattern
before_script:
  - cd $WORKDIR
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B